# Generated by Django 4.2.1 on 2023-06-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255, verbose_name=' Имя продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='фотография'),
        ),
    ]
